// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBz76DzXtOmCvujwNh6zDtq2wWVxCD1Q',
    appId: '1:718241966892:web:3eb1ab228de2c196a91a89',
    messagingSenderId: '718241966892',
    projectId: 'mydentlog',
    authDomain: 'mydentlog.firebaseapp.com',
    databaseURL: 'https://mydentlog-default-rtdb.firebaseio.com',
    storageBucket: 'mydentlog.firebasestorage.app',
    measurementId: 'G-5HBNNDCCT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQW0_xQ7VpWq7KLsB319_G_w5HqtQBsw',
    appId: '1:718241966892:android:23a6585a01f519b2a91a89',
    messagingSenderId: '718241966892',
    projectId: 'mydentlog',
    databaseURL: 'https://mydentlog-default-rtdb.firebaseio.com',
    storageBucket: 'mydentlog.firebasestorage.app',
  );

}